# config.yaml
api_keys:
  bing_api_key: "629329cba3d34ef79d3fd0bd3a1316f5"
  bing_custom_config_id: "6a5e9819-01a2-499f-9bce-c029385741ec"

# MT5 Configuration
mt5_credentials:
  account_number: "213201143"
  password: "Y4&seP6U"
  server: "OctaFX-Demo"

# Asset Configuration
assets:
  - "EURUSD"
  - "GBPUSD"
  - "USDJPY"
  - "XAUUSD"

# Data Collection Configuration
data_config:
  timeframe: "1h"
  history_period: "2y"
  resample_frequency: "1h"
  yf_period: "2y"
  yf_interval: "1h"

# Preprocessing Configuration
preprocessing:
  lookback_period: 100
  train_test_split: 0.2
  feature_columns:
    - "Open"
    - "High"
    - "Low"
    - "Close"
    - "Volume"
    - "positive"
    - "negative"
    - "neutral"
    - "Returns"
    - "RSI"
    - "Momentum"
    - "ROC"

# Model Configuration
model_params:
  confidence_threshold: 0.75
  sequence_length: 60  # Unified sequence length
  lstm:
    layers: [128, 64, 32]
    dropout: 0.2
    epochs: 100
    batch_size: 32
    optimizer:
      type: "adam"
      learning_rate: 0.001

# Trading Strategies Configuration
strategies:
  ma_crossover:
    short_window: 20
    long_window: 50
    min_slope: 0.01
  rsi:
    period: 14
    overbought: 70
    oversold: 30
  bollinger:
    window: 20
    num_std: 2

# Risk Management Configuration
risk_management:
  take_profit: 0.02
  stop_loss: 0.01
  base_position_size: 0.1
  max_position_size: 1.0
  max_open_positions: 3
  max_daily_loss: 0.05
  max_risk_per_trade: 0.01  # Added this line
  max_leverage: 30  # Added this line

# System Configuration
system:
  analysis_interval: 1800  # in seconds
  log_level: "INFO"
  data_directory: "data"
  log_directory: "logs"

# News Configuration
news_config:
  retention_days: 7
  max_articles: 100
  update_interval: 3600  # in seconds