# config.yaml
api_keys:
  bing_api_key: "629329cba3d34ef79d3fd0bd3a1316f5"
  bing_custom_config_id: "6a5e9819-01a2-499f-9bce-c029385741ec"
  mt4_token: "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIwZWEzYjQwMGVhNmUyMDE1YmU0MjdjZDlkZjY2YTVlOSIsInBlcm1pc3Npb25zIjpbXSwiYWNjZXNzUnVsZXMiOlt7ImlkIjoidHJhZGluZy1hY2NvdW50LW1hbmFnZW1lbnQtYXBpIiwibWV0aG9kcyI6WyJ0cmFkaW5nLWFjY291bnQtbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciJdLCJyZXNvdXJjZXMiOlsiYWNjb3VudDokVVNFUl9JRCQ6ZWZkNDQxZmEtMjk5Mi00MDgwLWExZTMtZDM4ODk3NmE2NzY3Il19LHsiaWQiOiJtZXRhYXBpLXJlc3QtYXBpIiwibWV0aG9kcyI6WyJtZXRhYXBpLWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyJhY2NvdW50OiRVU0VSX0lEJDplZmQ0NDFmYS0yOTkyLTQwODAtYTFlMy1kMzg4OTc2YTY3NjciXX0seyJpZCI6Im1ldGFhcGktcnBjLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbImFjY291bnQ6JFVTRVJfSUQkOmVmZDQ0MWZhLTI5OTItNDA4MC1hMWUzLWQzODg5NzZhNjc2NyJdfSx7ImlkIjoibWV0YWFwaS1yZWFsLXRpbWUtc3RyZWFtaW5nLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbImFjY291bnQ6JFVTRVJfSUQkOmVmZDQ0MWZhLTI5OTItNDA4MC1hMWUzLWQzODg5NzZhNjc2NyJdfSx7ImlkIjoibWV0YXN0YXRzLWFwaSIsIm1ldGhvZHMiOlsibWV0YXN0YXRzLWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIl0sInJlc291cmNlcyI6WyJhY2NvdW50OiRVU0VSX0lEJDplZmQ0NDFmYS0yOTkyLTQwODAtYTFlMy1kMzg4OTc2YTY3NjciXX0seyJpZCI6InJpc2stbWFuYWdlbWVudC1hcGkiLCJtZXRob2RzIjpbInJpc2stbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciJdLCJyZXNvdXJjZXMiOlsiYWNjb3VudDokVVNFUl9JRCQ6ZWZkNDQxZmEtMjk5Mi00MDgwLWExZTMtZDM4ODk3NmE2NzY3Il19LHsiaWQiOiJtdC1tYW5hZ2VyLWFwaSIsIm1ldGhvZHMiOlsibXQtbWFuYWdlci1hcGk6cmVzdDpkZWFsaW5nOio6KiIsIm10LW1hbmFnZXItYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX1dLCJ0b2tlbklkIjoiMjAyMTAyMTMiLCJpbXBlcnNvbmF0ZWQiOmZhbHNlLCJyZWFsVXNlcklkIjoiMGVhM2I0MDBlYTZlMjAxNWJlNDI3Y2Q5ZGY2NmE1ZTkiLCJpYXQiOjE3Mjk0MzM0NDZ9.l6gqRT0Q0PD6Ukm5mYiEYoOMmmZDYY09ttXiiy-iVsPX1VsBDqZsF6j0ljjIFntTum0TMTzDF0709s3S3LYkMpJlU6Z2A7y-8Fonju7AAxaPFTaFjZ7ytE5zaup5Mw5Jkoy_RpkBawjlzwdQK7v6olEwMiyIAErYfu6GthMllIBozsM2zFLFodevkp58UJ5ALvWpSQixN2TRkjBsxCDpKKJwXI5PYh-Pi3xrgKQ0H0j7EPjkSiN8RfhSULJtoBXNH8EqeRgbPifvrREhrYelRlKElN9s6Ns2CALZ-zGYy1pAmKCizwv_zUM9_0ryQ3yukvSGpSpM3Aj4sh7zgQX13PuRfO1NKLevRV4NplSicNl1oZkxfHTOmfq6IkcItmqtQ5jNsYnDdiukksWoQ-Zi6-6E1uX5uLmVKfuXK7oOd4vpXkAXOBiYcI9lcNBv1r_lR0C4V4SY0mnpegveP7gE69ywIXU8D5K_Odi0VkHgjTXpgBi5yeWosNn5IbB_jS_Pur-cEeCTF1cBFb2hkINw9hS0o0QDwSAsdoMnfK1FER5y1Vt-Oim50G6CaW_Dsz8g9__CzTG-1ULK9TfFf8GFI0YeMZEIoNxH4aspGtrRgVMwyfL3Xr-EHpRpFy2uhNJlK9dM01Mczl1v4ZhpXWxkbfc6Q8SYs294OaqNGS1thSA"
  mt4_account_id: "efd441fa-2992-4080-a1e3-d388976a6767"
  domain: "agiliumtrade.agiliumtrade.ai"

assets:
  - "EURUSD"
  - "GBPUSD"
  - "USDJPY"
  - "XAUUSD"

data_config:
  timeframe: "1h"
  history_period: "2y"
  resample_frequency: "1h"

preprocessing:
  lookback_period: 100
  train_test_split: 0.2

model_params:
  lstm:
    epochs: 50
    batch_size: 32
    sequence_length: 60
    units: 50
    dropout: 0.2

strategies:
  ma_crossover:
    short_window: 20
    long_window: 50
  rsi:
    period: 14
    overbought: 70
    oversold: 30
  bollinger:
    window: 20
    num_std: 2

risk_management:
  max_position_size: 0.02  # 2% of portfolio
  stop_loss: 0.01  # 1% stop loss
  take_profit: 0.02  # 2% take profit
  max_daily_loss: 0.05  # 5% max daily loss

news_config:
  update_interval: 3600  # seconds
  retention_days: 7
  max_articles: 100
