# config.yaml
api_keys:
  bing_api_key: "629329cba3d34ef79d3fd0bd3a1316f5"
  bing_custom_config_id: "6a5e9819-01a2-499f-9bce-c029385741ec"
  mt4_token: "eeyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIwZWEzYjQwMGVhNmUyMDE1YmU0MjdjZDlkZjY2YTVlOSIsInBlcm1pc3Npb25zIjpbXSwiYWNjZXNzUnVsZXMiOlt7ImlkIjoidHJhZGluZy1hY2NvdW50LW1hbmFnZW1lbnQtYXBpIiwibWV0aG9kcyI6WyJ0cmFkaW5nLWFjY291bnQtbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciJdLCJyZXNvdXJjZXMiOlsiYWNjb3VudDokVVNFUl9JRCQ6MTE5MDhjMGQtNWM2ZC00ZTcxLThhMmUtMjY2OTIwZmEyYzZjIl19LHsiaWQiOiJtZXRhYXBpLXJlc3QtYXBpIiwibWV0aG9kcyI6WyJtZXRhYXBpLWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyJhY2NvdW50OiRVU0VSX0lEJDoxMTkwOGMwZC01YzZkLTRlNzEtOGEyZS0yNjY5MjBmYTJjNmMiXX0seyJpZCI6Im1ldGFhcGktcnBjLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbImFjY291bnQ6JFVTRVJfSUQkOjExOTA4YzBkLTVjNmQtNGU3MS04YTJlLTI2NjkyMGZhMmM2YyJdfSx7ImlkIjoibWV0YWFwaS1yZWFsLXRpbWUtc3RyZWFtaW5nLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbImFjY291bnQ6JFVTRVJfSUQkOjExOTA4YzBkLTVjNmQtNGU3MS04YTJlLTI2NjkyMGZhMmM2YyJdfSx7ImlkIjoibWV0YXN0YXRzLWFwaSIsIm1ldGhvZHMiOlsibWV0YXN0YXRzLWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIl0sInJlc291cmNlcyI6WyJhY2NvdW50OiRVU0VSX0lEJDoxMTkwOGMwZC01YzZkLTRlNzEtOGEyZS0yNjY5MjBmYTJjNmMiXX0seyJpZCI6InJpc2stbWFuYWdlbWVudC1hcGkiLCJtZXRob2RzIjpbInJpc2stbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciJdLCJyZXNvdXJjZXMiOlsiYWNjb3VudDokVVNFUl9JRCQ6MTE5MDhjMGQtNWM2ZC00ZTcxLThhMmUtMjY2OTIwZmEyYzZjIl19LHsiaWQiOiJjb3B5ZmFjdG9yeS1hcGkiLCJtZXRob2RzIjpbImNvcHlmYWN0b3J5LWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJtdC1tYW5hZ2VyLWFwaSIsIm1ldGhvZHMiOlsibXQtbWFuYWdlci1hcGk6cmVzdDpkZWFsaW5nOio6KiIsIm10LW1hbmFnZXItYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6ImJpbGxpbmctYXBpIiwibWV0aG9kcyI6WyJiaWxsaW5nLWFwaTpyZXN0OnB1YmxpYzpwYXltZW50OioiXSwicm9sZXMiOlsicmVhZGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19XSwidG9rZW5JZCI6IjIwMjEwMjEzIiwiaW1wZXJzb25hdGVkIjpmYWxzZSwicmVhbFVzZXJJZCI6IjBlYTNiNDAwZWE2ZTIwMTViZTQyN2NkOWRmNjZhNWU5IiwiaWF0IjoxNzMwMjQyNDUyfQ.nkpqa81u66qR5ZGG7wbtYkPWUFbigTzX49nIIDaf5yOSYWdmqUaAbfFLPLPUcNiiUScrw_-oTR6Thdlo7yf4ooOz_Z7O8unz5qC-C8iNpyJFmhj7J5uw5iwVmymPtsDADY9iaMrxtNvUr6i8LdTOebMSNk_pR84dNyEXUuqxpGw5T1iUqKL4mgeSsS7ARN79WUTHEi-eLUZPDXSlU_PItceO54WjbKPyMimW7C_4EARRefW3pp5UhKGUpvZnKlUnIaFHm9fvRWdkHkkRKPKmQbseO-pnVkYdxzh-ZClf0i21NNwkJJmsq7hBkYohrmKZ0bIpmbpAsYN35KNO69_mqvcbNkxXziehSLPOB0fuXPg4W1j-UZbuw6pRw_8gUtw0Q4pno5uv9sKrI21lUKXsltpyWHvc5VP_Ku1oTUrYH8nVjBlRUl6pcWMhw0Q1cNN0BaoE_Nj2-BHgvRYGRXbfbA0jU4TNOm1k6bUdIa6RtzWc19lmLOewTfBaTkyKUfXBeJNyU21eOhkm6_Z91cRKCkeFC3QZ4HGPnYBIG03af3QG9CeXHnRdLMohqFgbKVUkI0zYVBX6KX1wPUkADl14ff2umWc7XqOG-iVlHPNJWIm3MuJaUaA-nDc7NpkrHOitDMjBeP8Oc5X4M6ziiesy8FodW_WXFRSJXpEXumf4Nqw"
  mt4_account_id: "11908c0d-5c6d-4e71-8a2e-266920fa2c6c"
  domain: "agiliumtrade.agiliumtrade.ai"

assets:
  - "EURUSD"
  - "GBPUSD"
  - "USDJPY"
  - "XAUUSD"

data_config:
  timeframe: "1h"
  history_period: "2y"
  resample_frequency: "1h"

preprocessing:
  lookback_period: 100
  train_test_split: 0.2

model_params:
  lstm:
    epochs: 50
    batch_size: 32
    sequence_length: 60
    units: 50
    dropout: 0.2

strategies:
  ma_crossover:
    short_window: 20
    long_window: 50
  rsi:
    period: 14
    overbought: 70
    oversold: 30
  bollinger:
    window: 20
    num_std: 2

risk_management:
  max_position_size: 0.02  # 2% of portfolio
  stop_loss: 0.01  # 1% stop loss
  take_profit: 0.02  # 2% take profit
  max_daily_loss: 0.05  # 5% max daily loss

news_config:
  update_interval: 3600  # seconds
  retention_days: 7
  max_articles: 100
