# config.yaml
api_keys:
  bing_api_key: "629329cba3d34ef79d3fd0bd3a1316f5"
  bing_custom_config_id: "6a5e9819-01a2-499f-9bce-c029385741ec"
  mt4_token: "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIwZWEzYjQwMGVhNmUyMDE1YmU0MjdjZDlkZjY2YTVlOSIsInBlcm1pc3Npb25zIjpbXSwiYWNjZXNzUnVsZXMiOlt7ImlkIjoidHJhZGluZy1hY2NvdW50LW1hbmFnZW1lbnQtYXBpIiwibWV0aG9kcyI6WyJ0cmFkaW5nLWFjY291bnQtbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibWV0YWFwaS1yZXN0LWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibWV0YWFwaS1ycGMtYXBpIiwibWV0aG9kcyI6WyJtZXRhYXBpLWFwaTp3czpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibWV0YWFwaS1yZWFsLXRpbWUtc3RyZWFtaW5nLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFzdGF0cy1hcGkiLCJtZXRob2RzIjpbIm1ldGFzdGF0cy1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoicmlzay1tYW5hZ2VtZW50LWFwaSIsIm1ldGhvZHMiOlsicmlzay1tYW5hZ2VtZW50LWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJjb3B5ZmFjdG9yeS1hcGkiLCJtZXRob2RzIjpbImNvcHlmYWN0b3J5LWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJtdC1tYW5hZ2VyLWFwaSIsIm1ldGhvZHMiOlsibXQtbWFuYWdlci1hcGk6cmVzdDpkZWFsaW5nOio6KiIsIm10LW1hbmFnZXItYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6ImJpbGxpbmctYXBpIiwibWV0aG9kcyI6WyJiaWxsaW5nLWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19XSwidG9rZW5JZCI6IjIwMjEwMjEzIiwiaW1wZXJzb25hdGVkIjpmYWxzZSwicmVhbFVzZXJJZCI6IjBlYTNiNDAwZWE2ZTIwMTViZTQyN2NkOWRmNjZhNWU5IiwiaWF0IjoxNzMwMjQzODE1fQ.YNR6H7uqt8hU1xocZN0nOADoN7EkDz7RuutaXqISKbUbi_G0WkAxvI5if6I1rgx_PcyQkBm-UDBtd-Ji34vw5mAsQnNdXgyOTHV749_cyGbUpLfn_iTVMKzithXkHjBdYtktHnctYYA1M_q3g3HQp5Gkflcsp54HNI0ZThNEw0x9T8SAIOtdl9mYCnpaGb5oC-Oj43hX5lVqC0i9MLDEBhwSAT6ZkowcHOnYpQQc9N3M_WJOnFNKVSfkeo_ZkdYuBzI1kHHuJH4hFBccpVoV1oxjYTFZCpPgpQuvdzYE22p90crOEDzts3ShSwITfGGzs3Y_D3vh0bpEfMegP1QddEwsVGteFWJtwzSgOs05YMyDtYq_Skq6s144b_U9rDDizfRCLf-LJ3CXL8mG7XCAaHRen5ER583izCPdcTIUX3kwZTvgLo-5zlcE-1l2Ex1IwYb_AW1X8OxZXI2V8PFzjz_W2ygwVSWfn26xwOEB0krolETCxNMScNep5xkqtvl1Cls0TIUZuKmP_-Cs2WvcRMcOdTTr-z16ynif3Anz2X5qZpsZBS-h4WedU1m4P2HnPGHkyXN4OB5QfzMKzesFYOd9jZNJnT9g5P0DIUswrHGj45GCEU8-fDYv5-mSop4mSHCXzu6eeMszB-Gq9m7m5qsAVtU3fvJ11khxVCsL6pY"
  mt4_account_id: "11908c0d-5c6d-4e71-8a2e-266920fa2c6c"
  domain: "agiliumtrade.agiliumtrade.ai"

assets:
  - "EURUSD"
  - "GBPUSD"
  - "USDJPY"
  - "XAUUSD"

data_config:
  timeframe: "1h"
  history_period: "2y"
  resample_frequency: "1h"

preprocessing:
  lookback_period: 100
  train_test_split: 0.2

model_params:
  lstm:
    epochs: 50
    batch_size: 32
    sequence_length: 60
    units: 50
    dropout: 0.2

strategies:
  ma_crossover:
    short_window: 20
    long_window: 50
  rsi:
    period: 14
    overbought: 70
    oversold: 30
  bollinger:
    window: 20
    num_std: 2

risk_management:
  max_position_size: 0.02  # 2% of portfolio
  stop_loss: 0.01  # 1% stop loss
  take_profit: 0.02  # 2% take profit
  max_daily_loss: 0.05  # 5% max daily loss

news_config:
  update_interval: 3600  # seconds
  retention_days: 7
  max_articles: 100
sequence_length: 50  # Add this line with an appropriate value