# config.yaml
api_keys:
  bing_api_key: "ecdf681361ae49e0a132d86b1329e532"
  bing_custom_config_id: "6a5e9819-01a2-499f-9bce-c029385741ec"
  mt4_token: "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIwZWEzYjQwMGVhNmUyMDE1YmU0MjdjZDlkZjY2YTVlOSIsInBlcm1pc3Npb25zIjpbXSwiYWNjZXNzUnVsZXMiOlt7ImlkIjoidHJhZGluZy1hY2NvdW50LW1hbmFnZW1lbnQtYXBpIiwibWV0aG9kcyI6WyJ0cmFkaW5nLWFjY291bnQtbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibWV0YWFwaS1yZXN0LWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibWV0YWFwaS1ycGMtYXBpIiwibWV0aG9kcyI6WyJtZXRhYXBpLWFwaTp3czpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibWV0YWFwaS1yZWFsLXRpbWUtc3RyZWFtaW5nLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFzdGF0cy1hcGkiLCJtZXRob2RzIjpbIm1ldGFzdGF0cy1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoicmlzay1tYW5hZ2VtZW50LWFwaSIsIm1ldGhvZHMiOlsicmlzay1tYW5hZ2VtZW50LWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJjb3B5ZmFjdG9yeS1hcGkiLCJtZXRob2RzIjpbImNvcHlmYWN0b3J5LWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJtdC1tYW5hZ2VyLWFwaSIsIm1ldGhvZHMiOlsibXQtbWFuYWdlci1hcGk6cmVzdDpkZWFsaW5nOio6KiIsIm10LW1hbmFnZXItYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6ImJpbGxpbmctYXBpIiwibWV0aG9kcyI6WyJiaWxsaW5nLWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19XSwidG9rZW5JZCI6IjIwMjEwMjEzIiwiaW1wZXJzb25hdGVkIjpmYWxzZSwicmVhbFVzZXJJZCI6IjBlYTNiNDAwZWE2ZTIwMTViZTQyN2NkOWRmNjZhNWU5IiwiaWF0IjoxNzMwMTQ1MTY3fQ.Y_srriv7X3Nt99L1m0t1QerUOwxWBPQB4q2eH8SSxnZyfqwMhJ8RTE29xFDo6mi9RwEq3MPqeikbyDDo2haV_EVRvvkNT3hdKE2NtSyZMasBzwEnJA0lGZIA5ghBr2iFNGDC8Q6POTrkjS0Ypu-2zw6Ale7Zv1jPt6Kv3VtLPrK3_oVeVR8BwquwbjhQMEqmn_GZWWhR1yNR2sFBcDnB4gHSNCsFXakknXOTRgqHJBa8SnhHbGn4GSHf-lHhTqtuHPzO8OMN1OrBqN5W0enudKUYA5IscQkubyAuKF9_afL_4fuuiCR_DpeCh3G0qtZLAc83RlbeS6B2lH5ZNsI7B8acSmPXGXpctYaZmpLydZg4SWBDywTjEdwEMAFO8kt3CmI4uUKH_SRZJ7KFlMdbh8pX8ipGx7hOTeBq-93Zi3tpSchrkQFkX0Ejz8iLknsdq_KAh5xy0DclXJ9w_dGSN5lmUiLcxKIKIlL0pVj8KfvmzfwxZfOHVxwGojNJTGTVRbt3bnDduMRb01RNSkOy552SV5rYpwPTp8rSz3msWnyai7j0cjTi-ztLXqcPXnFFRv-hqW_TxqaX4zk_URRZFHN676CpXuT-5WjACcnVHhhjIVTIaO1X-HQWAlJF5t4RjMQsAMkqsTm3B3int8I0t2K5TZ9HxjbYDUbARyufsB8"
  mt4_account_id: "b62d8ee1-4a18-4f19-9ddf-aceaab21221f"
  domain: "agiliumtrade.agiliumtrade.ai"

assets:
  - "EURUSD"
  - "GBPUSD"
  - "USDJPY"
  - "XAUUSD"

data_config:
  timeframe: "1h"
  history_period: "2y"
  resample_frequency: "1h"

preprocessing:
  lookback_period: 100
  train_test_split: 0.2

model_params:
  lstm:
    epochs: 50
    batch_size: 32
    sequence_length: 60
    units: 50
    dropout: 0.2

strategies:
  ma_crossover:
    short_window: 20
    long_window: 50
  rsi:
    period: 14
    overbought: 70
    oversold: 30
  bollinger:
    window: 20
    num_std: 2

risk_management:
  max_position_size: 0.02  # 2% of portfolio
  stop_loss: 0.01  # 1% stop loss
  take_profit: 0.02  # 2% take profit
  max_daily_loss: 0.05  # 5% max daily loss

news_config:
  update_interval: 3600  # seconds
  retention_days: 7
  max_articles: 100
